name: Release and Publish Extension

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - test

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: node setup
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: install deps
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: package vsix
        run: pnpm run build

      - name: github release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            *.vsix